//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KactusIntegration
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empleado", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class Empleado : object
    {
        
        private string CargoField;
        
        private string CargoEmpleadoField;
        
        private string CelularField;
        
        private string CentroCostoField;
        
        private string CodCiudadExpedicionField;
        
        private string CodCiudadResidenciaField;
        
        private string CodDeptoExpedicionField;
        
        private string CodDeptoResidenciaField;
        
        private long CodTipoEspPersonaPreliqField;
        
        private long CodTipoPersonaField;
        
        private long CodUbicacionField;
        
        private string CodigoAreaField;
        
        private short CodigoEmpresaField;
        
        private string CodigoGrupoField;
        
        private string CodigoNivelField;
        
        private int CodigoNivel1Field;
        
        private int CodigoNivel2Field;
        
        private int CodigoNivel3Field;
        
        private int CodigoNivel4Field;
        
        private int CodigoNivel5Field;
        
        private int CodigoNivel6Field;
        
        private int CodigoNivel7Field;
        
        private string DireccionField;
        
        private string EmailField;
        
        private string EpsField;
        
        private string EscalaSalarialField;
        
        private string EstadoEmpleadoField;
        
        private string ExtensionCompaniaField;
        
        private System.DateTime FecActCargoField;
        
        private System.DateTime FecActContrField;
        
        private string FechaInicioContratoField;
        
        private System.DateTime FechaNacimientoField;
        
        private string GanaExtrasField;
        
        private string GeneroField;
        
        private string IdentificacionExternaField;
        
        private string NombreNivelField;
        
        private string NombreNivel1Field;
        
        private string NombreNivel2Field;
        
        private string NombreNivel3Field;
        
        private string NombreNivel4Field;
        
        private string NombreNivel5Field;
        
        private string NombreNivel6Field;
        
        private string NombreNivel7Field;
        
        private string NumeroContratoField;
        
        private long NumeroDeIdentificacionField;
        
        private string PrimerApellidoField;
        
        private string PrimerNombreField;
        
        private string PuedeSerVisitadoField;
        
        private string RhField;
        
        private string SegundoApellidoField;
        
        private string SegundoNombreField;
        
        private string TelefonoField;
        
        private string TemporalField;
        
        private string TipoContratistaField;
        
        private string TipoDeIdentificacionField;
        
        private string TipoDeSangreField;
        
        private bool TitularField;
        
        private string ValidoParaLiqNominaField;
        
        private long VencimientoAccionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cargo
        {
            get
            {
                return this.CargoField;
            }
            set
            {
                this.CargoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CargoEmpleado
        {
            get
            {
                return this.CargoEmpleadoField;
            }
            set
            {
                this.CargoEmpleadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Celular
        {
            get
            {
                return this.CelularField;
            }
            set
            {
                this.CelularField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CentroCosto
        {
            get
            {
                return this.CentroCostoField;
            }
            set
            {
                this.CentroCostoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodCiudadExpedicion
        {
            get
            {
                return this.CodCiudadExpedicionField;
            }
            set
            {
                this.CodCiudadExpedicionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodCiudadResidencia
        {
            get
            {
                return this.CodCiudadResidenciaField;
            }
            set
            {
                this.CodCiudadResidenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodDeptoExpedicion
        {
            get
            {
                return this.CodDeptoExpedicionField;
            }
            set
            {
                this.CodDeptoExpedicionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodDeptoResidencia
        {
            get
            {
                return this.CodDeptoResidenciaField;
            }
            set
            {
                this.CodDeptoResidenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CodTipoEspPersonaPreliq
        {
            get
            {
                return this.CodTipoEspPersonaPreliqField;
            }
            set
            {
                this.CodTipoEspPersonaPreliqField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CodTipoPersona
        {
            get
            {
                return this.CodTipoPersonaField;
            }
            set
            {
                this.CodTipoPersonaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CodUbicacion
        {
            get
            {
                return this.CodUbicacionField;
            }
            set
            {
                this.CodUbicacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoArea
        {
            get
            {
                return this.CodigoAreaField;
            }
            set
            {
                this.CodigoAreaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short CodigoEmpresa
        {
            get
            {
                return this.CodigoEmpresaField;
            }
            set
            {
                this.CodigoEmpresaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoGrupo
        {
            get
            {
                return this.CodigoGrupoField;
            }
            set
            {
                this.CodigoGrupoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoNivel
        {
            get
            {
                return this.CodigoNivelField;
            }
            set
            {
                this.CodigoNivelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoNivel1
        {
            get
            {
                return this.CodigoNivel1Field;
            }
            set
            {
                this.CodigoNivel1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoNivel2
        {
            get
            {
                return this.CodigoNivel2Field;
            }
            set
            {
                this.CodigoNivel2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoNivel3
        {
            get
            {
                return this.CodigoNivel3Field;
            }
            set
            {
                this.CodigoNivel3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoNivel4
        {
            get
            {
                return this.CodigoNivel4Field;
            }
            set
            {
                this.CodigoNivel4Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoNivel5
        {
            get
            {
                return this.CodigoNivel5Field;
            }
            set
            {
                this.CodigoNivel5Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoNivel6
        {
            get
            {
                return this.CodigoNivel6Field;
            }
            set
            {
                this.CodigoNivel6Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoNivel7
        {
            get
            {
                return this.CodigoNivel7Field;
            }
            set
            {
                this.CodigoNivel7Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion
        {
            get
            {
                return this.DireccionField;
            }
            set
            {
                this.DireccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Eps
        {
            get
            {
                return this.EpsField;
            }
            set
            {
                this.EpsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EscalaSalarial
        {
            get
            {
                return this.EscalaSalarialField;
            }
            set
            {
                this.EscalaSalarialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoEmpleado
        {
            get
            {
                return this.EstadoEmpleadoField;
            }
            set
            {
                this.EstadoEmpleadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExtensionCompania
        {
            get
            {
                return this.ExtensionCompaniaField;
            }
            set
            {
                this.ExtensionCompaniaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FecActCargo
        {
            get
            {
                return this.FecActCargoField;
            }
            set
            {
                this.FecActCargoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FecActContr
        {
            get
            {
                return this.FecActContrField;
            }
            set
            {
                this.FecActContrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaInicioContrato
        {
            get
            {
                return this.FechaInicioContratoField;
            }
            set
            {
                this.FechaInicioContratoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaNacimiento
        {
            get
            {
                return this.FechaNacimientoField;
            }
            set
            {
                this.FechaNacimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GanaExtras
        {
            get
            {
                return this.GanaExtrasField;
            }
            set
            {
                this.GanaExtrasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Genero
        {
            get
            {
                return this.GeneroField;
            }
            set
            {
                this.GeneroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentificacionExterna
        {
            get
            {
                return this.IdentificacionExternaField;
            }
            set
            {
                this.IdentificacionExternaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreNivel
        {
            get
            {
                return this.NombreNivelField;
            }
            set
            {
                this.NombreNivelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreNivel1
        {
            get
            {
                return this.NombreNivel1Field;
            }
            set
            {
                this.NombreNivel1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreNivel2
        {
            get
            {
                return this.NombreNivel2Field;
            }
            set
            {
                this.NombreNivel2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreNivel3
        {
            get
            {
                return this.NombreNivel3Field;
            }
            set
            {
                this.NombreNivel3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreNivel4
        {
            get
            {
                return this.NombreNivel4Field;
            }
            set
            {
                this.NombreNivel4Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreNivel5
        {
            get
            {
                return this.NombreNivel5Field;
            }
            set
            {
                this.NombreNivel5Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreNivel6
        {
            get
            {
                return this.NombreNivel6Field;
            }
            set
            {
                this.NombreNivel6Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreNivel7
        {
            get
            {
                return this.NombreNivel7Field;
            }
            set
            {
                this.NombreNivel7Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroContrato
        {
            get
            {
                return this.NumeroContratoField;
            }
            set
            {
                this.NumeroContratoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long NumeroDeIdentificacion
        {
            get
            {
                return this.NumeroDeIdentificacionField;
            }
            set
            {
                this.NumeroDeIdentificacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimerApellido
        {
            get
            {
                return this.PrimerApellidoField;
            }
            set
            {
                this.PrimerApellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimerNombre
        {
            get
            {
                return this.PrimerNombreField;
            }
            set
            {
                this.PrimerNombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PuedeSerVisitado
        {
            get
            {
                return this.PuedeSerVisitadoField;
            }
            set
            {
                this.PuedeSerVisitadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rh
        {
            get
            {
                return this.RhField;
            }
            set
            {
                this.RhField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SegundoApellido
        {
            get
            {
                return this.SegundoApellidoField;
            }
            set
            {
                this.SegundoApellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SegundoNombre
        {
            get
            {
                return this.SegundoNombreField;
            }
            set
            {
                this.SegundoNombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                this.TelefonoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Temporal
        {
            get
            {
                return this.TemporalField;
            }
            set
            {
                this.TemporalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoContratista
        {
            get
            {
                return this.TipoContratistaField;
            }
            set
            {
                this.TipoContratistaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDeIdentificacion
        {
            get
            {
                return this.TipoDeIdentificacionField;
            }
            set
            {
                this.TipoDeIdentificacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDeSangre
        {
            get
            {
                return this.TipoDeSangreField;
            }
            set
            {
                this.TipoDeSangreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Titular
        {
            get
            {
                return this.TitularField;
            }
            set
            {
                this.TitularField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValidoParaLiqNomina
        {
            get
            {
                return this.ValidoParaLiqNominaField;
            }
            set
            {
                this.ValidoParaLiqNominaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long VencimientoAccion
        {
            get
            {
                return this.VencimientoAccionField;
            }
            set
            {
                this.VencimientoAccionField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KactusIntegration.IKWsGhst2")]
    public interface IKWsGhst2
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKWsGhst2/ConsultarEmpleados", ReplyAction="http://tempuri.org/IKWsGhst2/ConsultarEmpleadosResponse")]
        System.Threading.Tasks.Task<KactusIntegration.Empleado[]> ConsultarEmpleadosAsync(int codigoEmpresa, System.DateTime ultimaFechaConsulta, string usuario, string contrasenhia);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    public interface IKWsGhst2Channel : KactusIntegration.IKWsGhst2, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    public partial class KWsGhst2Client : System.ServiceModel.ClientBase<KactusIntegration.IKWsGhst2>, KactusIntegration.IKWsGhst2
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public KWsGhst2Client() : 
                base(KWsGhst2Client.GetDefaultBinding(), KWsGhst2Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IKWsGhst2.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KWsGhst2Client(EndpointConfiguration endpointConfiguration) : 
                base(KWsGhst2Client.GetBindingForEndpoint(endpointConfiguration), KWsGhst2Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KWsGhst2Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(KWsGhst2Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KWsGhst2Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(KWsGhst2Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KWsGhst2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<KactusIntegration.Empleado[]> ConsultarEmpleadosAsync(int codigoEmpresa, System.DateTime ultimaFechaConsulta, string usuario, string contrasenhia)
        {
            return base.Channel.ConsultarEmpleadosAsync(codigoEmpresa, ultimaFechaConsulta, usuario, contrasenhia);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IKWsGhst2))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IKWsGhst2))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.0.182:4818/KWsGhst2.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return KWsGhst2Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IKWsGhst2);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return KWsGhst2Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IKWsGhst2);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IKWsGhst2,
        }
    }
}
