// <auto-generated />
using System;
using Legalizaciones.Data.AppDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Legalizaciones.Data.Migrations
{
    [DbContext(typeof(AppDataContext))]
    partial class AppDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Legalizaciones.Model.Banco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Estatus");

                    b.Property<DateTime>("FechaCreacion");

                    b.Property<string>("Nombre")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Banco");
                });

            modelBuilder.Entity("Legalizaciones.Model.ConfiguracionGasto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cargo");

                    b.Property<string>("CargoId")
                        .IsRequired();

                    b.Property<string>("Descripcion")
                        .IsRequired();

                    b.Property<int?>("DestinoId");

                    b.Property<string>("DestinoNombre");

                    b.Property<int>("Estatus");

                    b.Property<DateTime>("FechaCreacion");

                    b.Property<bool>("GastoDiario");

                    b.Property<int>("MonedaId");

                    b.Property<string>("MonedaNombre");

                    b.Property<float>("Monto");

                    b.Property<int?>("OrigenId");

                    b.Property<string>("OrigenNombre");

                    b.Property<int>("PaisId");

                    b.Property<string>("PaisNombre");

                    b.Property<string>("TipoServicio");

                    b.Property<string>("TipoServicioId")
                        .IsRequired();

                    b.Property<int>("ZonaDestinoId");

                    b.Property<int>("ZonaOrigenId");

                    b.HasKey("Id");

                    b.HasIndex("DestinoId");

                    b.HasIndex("MonedaId");

                    b.HasIndex("OrigenId");

                    b.HasIndex("PaisId");

                    b.ToTable("ConfiguracionGasto");
                });

            modelBuilder.Entity("Legalizaciones.Model.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Apellido");

                    b.Property<string>("Area");

                    b.Property<int?>("CargoId");

                    b.Property<string>("Cedula")
                        .IsRequired();

                    b.Property<string>("CentroCostos");

                    b.Property<string>("CentroOperacion");

                    b.Property<string>("CentroOperaciones");

                    b.Property<string>("Ciudad");

                    b.Property<string>("Correo");

                    b.Property<string>("Direccion");

                    b.Property<int>("Estatus");

                    b.Property<DateTime>("FechaCreacion");

                    b.Property<string>("Nombre");

                    b.Property<string>("NombreSupervisor");

                    b.Property<int>("SupervisorId");

                    b.Property<string>("Telefono");

                    b.Property<string>("UnidadNegocio");

                    b.Property<string>("UnidadNegocios");

                    b.HasKey("Id");

                    b.ToTable("Empleado");
                });

            modelBuilder.Entity("Legalizaciones.Model.EmpleadoPermiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EmpleadoCedula");

                    b.Property<string>("EmpleadoPermisoCedula");

                    b.Property<string>("EmpleadoPermisoNombre");

                    b.Property<int>("Estatus");

                    b.Property<DateTime>("FechaCreacion");

                    b.Property<int>("TipoPermisoId");

                    b.HasKey("Id");

                    b.HasIndex("TipoPermisoId");

                    b.ToTable("EmpleadoPermiso");
                });

            modelBuilder.Entity("Legalizaciones.Model.FlujoSolicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Estatus");

                    b.Property<DateTime>("FechaCreacion");

                    b.Property<int>("PasoFlujoSolicitudId");

                    b.Property<int>("TipoSolicitudId");

                    b.HasKey("Id");

                    b.HasIndex("PasoFlujoSolicitudId");

                    b.HasIndex("TipoSolicitudId");

                    b.ToTable("FlujoSolicitud");
                });

            modelBuilder.Entity("Legalizaciones.Model.HistoricoSolicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descripcion");

                    b.Property<int>("Estatus");

                    b.Property<DateTime>("FechaCreacion");

                    b.Property<int>("FlujoSolicitudId");

                    b.Property<int>("PasoFlujoSolicitudId");

                    b.Property<int>("SolicitudId");

                    b.HasKey("Id");

                    b.HasIndex("FlujoSolicitudId");

                    b.HasIndex("PasoFlujoSolicitudId");

                    b.HasIndex("SolicitudId");

                    b.ToTable("HistoricoSolicitud");
                });

            modelBuilder.Entity("Legalizaciones.Model.ItemSolicitud.EstadoSolicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descripcion")
                        .IsRequired();

                    b.Property<int>("Estatus");

                    b.Property<DateTime>("FechaCreacion");

                    b.HasKey("Id");

                    b.ToTable("EstadoSolicitud");
                });

            modelBuilder.Entity("Legalizaciones.Model.ItemSolicitud.Moneda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Abreviatura");

                    b.Property<int>("Estatus");

                    b.Property<DateTime>("FechaCreacion");

                    b.Property<string>("Nombre")
                        .IsRequired();

                    b.Property<byte>("Simbolo");

                    b.HasKey("Id");

                    b.ToTable("Moneda");
                });

            modelBuilder.Entity("Legalizaciones.Model.ItemSolicitud.Tasa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Estatus");

                    b.Property<DateTime>("FechaCreacion");

                    b.Property<int>("MonedaId");

                    b.Property<string>("Valor")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("MonedaId");

                    b.ToTable("Tasa");
                });

            modelBuilder.Entity("Legalizaciones.Model.Jerarquia.Ciudad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Estatus");

                    b.Property<DateTime>("FechaCreacion");

                    b.Property<string>("Nombre")
                        .IsRequired();

                    b.Property<int>("PaisID");

                    b.HasKey("Id");

                    b.HasIndex("PaisID");

                    b.ToTable("Ciudad");
                });

            modelBuilder.Entity("Legalizaciones.Model.Jerarquia.Destino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Estatus");

                    b.Property<DateTime>("FechaCreacion");

                    b.Property<string>("Nombre")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Destino");
                });

            modelBuilder.Entity("Legalizaciones.Model.Jerarquia.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Abreviatura");

                    b.Property<int>("Estatus");

                    b.Property<DateTime>("FechaCreacion");

                    b.Property<string>("Nombre")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Pais");
                });

            modelBuilder.Entity("Legalizaciones.Model.Jerarquia.Zona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Abreviatura");

                    b.Property<int>("DestinoID");

                    b.Property<int>("Estatus");

                    b.Property<DateTime>("FechaCreacion");

                    b.Property<string>("Nombre")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("DestinoID");

                    b.ToTable("Zona");
                });

            modelBuilder.Entity("Legalizaciones.Model.Legalizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BancoId");

                    b.Property<long>("Consignacion");

                    b.Property<string>("EmpleadoCedula");

                    b.Property<int>("Estatus");

                    b.Property<DateTime>("FechaCreacion");

                    b.Property<long>("ReciboCaja");

                    b.Property<int>("SolicitudID");

                    b.Property<string>("Valor")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Legalizacion");
                });

            modelBuilder.Entity("Legalizaciones.Model.LegalizacionGastos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CentroCostosId");

                    b.Property<int>("CentroOperacionId");

                    b.Property<int>("CiudadId");

                    b.Property<string>("Concepto");

                    b.Property<int>("Estatus");

                    b.Property<DateTime>("FechaCreacion");

                    b.Property<DateTime>("FechaGasto");

                    b.Property<int?>("LegalizacionId");

                    b.Property<int>("MotivoId");

                    b.Property<int>("PaisId");

                    b.Property<int>("ProveedorId");

                    b.Property<int>("TipoServicioId");

                    b.Property<int>("UnidadNegocioId");

                    b.Property<string>("Valor");

                    b.HasKey("Id");

                    b.HasIndex("LegalizacionId");

                    b.ToTable("LegalizacionGastos");
                });

            modelBuilder.Entity("Legalizaciones.Model.PasoFlujoSolicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CedulaAprobador");

                    b.Property<string>("Descripcion");

                    b.Property<int>("Estatus");

                    b.Property<DateTime>("FechaCreacion");

                    b.Property<string>("NombreAprobador");

                    b.HasKey("Id");

                    b.ToTable("PasoFlujoSolicitud");
                });

            modelBuilder.Entity("Legalizaciones.Model.ServicioDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cargo");

                    b.Property<string>("Descripcion");

                    b.Property<int?>("DestinoId");

                    b.Property<int>("Estatus");

                    b.Property<DateTime>("FechaCreacion");

                    b.Property<float>("Monto");

                    b.Property<string>("Nombre")
                        .IsRequired();

                    b.Property<int?>("OrigenId");

                    b.Property<int>("PaisID");

                    b.Property<string>("Proveedor");

                    b.Property<int>("ProveedorID");

                    b.Property<string>("TipoServicio");

                    b.Property<int>("ZonaDestinoId");

                    b.Property<int>("ZonaOrigenId");

                    b.HasKey("Id");

                    b.HasIndex("DestinoId");

                    b.HasIndex("OrigenId");

                    b.HasIndex("PaisID");

                    b.ToTable("ServicioDetalle");
                });

            modelBuilder.Entity("Legalizaciones.Model.Solicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Banco");

                    b.Property<int>("CentroCostoId");

                    b.Property<int>("CentroOperacionId");

                    b.Property<string>("Concepto")
                        .IsRequired();

                    b.Property<int?>("DestinoID")
                        .IsRequired();

                    b.Property<string>("EmpleadoCedula");

                    b.Property<int?>("EstadoId");

                    b.Property<int>("Estatus");

                    b.Property<string>("Extracto");

                    b.Property<DateTime>("FechaCreacion");

                    b.Property<DateTime>("FechaDesde");

                    b.Property<DateTime>("FechaHasta");

                    b.Property<DateTime>("FechaSolicitud");

                    b.Property<DateTime>("FechaVencimiento");

                    b.Property<int?>("MonedaId")
                        .IsRequired();

                    b.Property<float>("Monto");

                    b.Property<string>("NumeroSolicitud");

                    b.Property<string>("RutaArchivo");

                    b.Property<int>("TipoSolicitudID");

                    b.Property<int>("UnidadNegocioId");

                    b.Property<int?>("ZonaID")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("DestinoID");

                    b.HasIndex("EstadoId");

                    b.HasIndex("MonedaId");

                    b.HasIndex("TipoSolicitudID");

                    b.HasIndex("ZonaID");

                    b.ToTable("Solicitud");
                });

            modelBuilder.Entity("Legalizaciones.Model.SolicitudGastos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Ciudad");

                    b.Property<int>("CiudadId");

                    b.Property<string>("Destino");

                    b.Property<int>("Estatus");

                    b.Property<DateTime>("FechaCreacion");

                    b.Property<string>("FechaGasto");

                    b.Property<string>("ICA");

                    b.Property<string>("IVA");

                    b.Property<string>("IVATeorico");

                    b.Property<float>("Monto");

                    b.Property<string>("Neto");

                    b.Property<string>("Origen");

                    b.Property<string>("Pais");

                    b.Property<int>("PaisId");

                    b.Property<string>("ReteIVA");

                    b.Property<string>("ReteServicio");

                    b.Property<string>("Servicio");

                    b.Property<int?>("ServicioId");

                    b.Property<int?>("SolicitudId");

                    b.HasKey("Id");

                    b.HasIndex("SolicitudId");

                    b.ToTable("SolicitudGastos");
                });

            modelBuilder.Entity("Legalizaciones.Model.TipoPermiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descripcion")
                        .IsRequired();

                    b.Property<int>("Estatus");

                    b.Property<DateTime>("FechaCreacion");

                    b.HasKey("Id");

                    b.ToTable("TipoPermiso");
                });

            modelBuilder.Entity("Legalizaciones.Model.TipoSolicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descripcion");

                    b.Property<int>("DiasHabiles");

                    b.Property<int>("Estatus");

                    b.Property<DateTime>("FechaCreacion");

                    b.Property<int>("FlujoSolicitudId");

                    b.Property<string>("Nombre")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("TipoSolicitud");
                });

            modelBuilder.Entity("Legalizaciones.Model.ConfiguracionGasto", b =>
                {
                    b.HasOne("Legalizaciones.Model.Jerarquia.Zona", "Destino")
                        .WithMany()
                        .HasForeignKey("DestinoId");

                    b.HasOne("Legalizaciones.Model.ItemSolicitud.Moneda", "Moneda")
                        .WithMany()
                        .HasForeignKey("MonedaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Legalizaciones.Model.Jerarquia.Zona", "Origen")
                        .WithMany()
                        .HasForeignKey("OrigenId");

                    b.HasOne("Legalizaciones.Model.Jerarquia.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Legalizaciones.Model.EmpleadoPermiso", b =>
                {
                    b.HasOne("Legalizaciones.Model.TipoPermiso", "TipoPermiso")
                        .WithMany()
                        .HasForeignKey("TipoPermisoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Legalizaciones.Model.FlujoSolicitud", b =>
                {
                    b.HasOne("Legalizaciones.Model.PasoFlujoSolicitud", "PasoFlujoSolicitud")
                        .WithMany()
                        .HasForeignKey("PasoFlujoSolicitudId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Legalizaciones.Model.TipoSolicitud", "TipoSolicitud")
                        .WithMany()
                        .HasForeignKey("TipoSolicitudId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Legalizaciones.Model.HistoricoSolicitud", b =>
                {
                    b.HasOne("Legalizaciones.Model.FlujoSolicitud", "FlujoSolicitud")
                        .WithMany()
                        .HasForeignKey("FlujoSolicitudId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Legalizaciones.Model.PasoFlujoSolicitud", "PasoFlujoSolicitud")
                        .WithMany()
                        .HasForeignKey("PasoFlujoSolicitudId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Legalizaciones.Model.Solicitud", "Solicitud")
                        .WithMany()
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Legalizaciones.Model.ItemSolicitud.Tasa", b =>
                {
                    b.HasOne("Legalizaciones.Model.ItemSolicitud.Moneda", "Moneda")
                        .WithMany()
                        .HasForeignKey("MonedaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Legalizaciones.Model.Jerarquia.Ciudad", b =>
                {
                    b.HasOne("Legalizaciones.Model.Jerarquia.Pais", "Pais")
                        .WithMany("Ciudad")
                        .HasForeignKey("PaisID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Legalizaciones.Model.Jerarquia.Zona", b =>
                {
                    b.HasOne("Legalizaciones.Model.Jerarquia.Destino", "Destino")
                        .WithMany("Ciudad")
                        .HasForeignKey("DestinoID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Legalizaciones.Model.LegalizacionGastos", b =>
                {
                    b.HasOne("Legalizaciones.Model.Legalizacion", "Legalizacion")
                        .WithMany()
                        .HasForeignKey("LegalizacionId");
                });

            modelBuilder.Entity("Legalizaciones.Model.ServicioDetalle", b =>
                {
                    b.HasOne("Legalizaciones.Model.Jerarquia.Zona", "Destino")
                        .WithMany()
                        .HasForeignKey("DestinoId");

                    b.HasOne("Legalizaciones.Model.Jerarquia.Zona", "Origen")
                        .WithMany()
                        .HasForeignKey("OrigenId");

                    b.HasOne("Legalizaciones.Model.Jerarquia.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("PaisID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Legalizaciones.Model.Solicitud", b =>
                {
                    b.HasOne("Legalizaciones.Model.Jerarquia.Destino", "Destino")
                        .WithMany()
                        .HasForeignKey("DestinoID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Legalizaciones.Model.ItemSolicitud.EstadoSolicitud", "EstadoSolicitud")
                        .WithMany()
                        .HasForeignKey("EstadoId");

                    b.HasOne("Legalizaciones.Model.ItemSolicitud.Moneda", "Moneda")
                        .WithMany()
                        .HasForeignKey("MonedaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Legalizaciones.Model.TipoSolicitud", "TipoSolicitud")
                        .WithMany()
                        .HasForeignKey("TipoSolicitudID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Legalizaciones.Model.Jerarquia.Zona", "Zona")
                        .WithMany()
                        .HasForeignKey("ZonaID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Legalizaciones.Model.SolicitudGastos", b =>
                {
                    b.HasOne("Legalizaciones.Model.Solicitud", "Solicitud")
                        .WithMany()
                        .HasForeignKey("SolicitudId");
                });
#pragma warning restore 612, 618
        }
    }
}
